[build]
  publish = "netlify-light"
  command = "npm run build && cp src/mp-favicon.svg dist/macknight-publications/ && mkdir -p netlify-light && cp -r dist/macknight-publications/browser/* netlify-light/ 2>/dev/null || cp -r dist/macknight-publications/* netlify-light/ && cp -r public/assets/images netlify-light/assets/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200